language: node_js

node_js:
- '12'
- '10'
- '8'

sudo: false

branches:
  except:
    - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+(@(alpha|beta))?)?$/

jobs:
  include:
    - stage: release
      node_js: 10
      script: skip
      before_deploy: npm install semantic-release@beta @traverson/semantic-release-config@alpha --no-save
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          all_branches: true

env:
  global:
    - FORCE_COLOR=1
    - NPM_CONFIG_COLOR=always
