language: node_js

node_js:
- '12'
- '10'
- '8'

sudo: false

branches:
  except:
    - /^v\d+\.\d+\.\d+(-(alpha|beta)\.\d+(@(alpha|beta))?)?$/

jobs:
  include:
    - stage: release
      node_js: 10
      script: skip
      before_deploy: npm install semantic-release@beta @traverson/semantic-release-config@alpha --no-save
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
        on:
          all_branches: true

env:
  global:
    - secure: mVi2+wUDrepjO9/3SU7xdxYmN+iOF62P7AQ2+ar3ODCZ2WaRNz8U1KdLG86RV3xpZJyw2en6yR7owefxtCZ1MYMCm7tu8r9oUUdcb2oA9DPsyzfRfZO2SanOeb90CJbu+7Mnu8/xGK12dNK9ckldIbjI4CnWa+zoLamMUjJA7IE=
    - FORCE_COLOR=1
    - NPM_CONFIG_COLOR=always
